### ISSUE TITLE
Number of marginals results year/subfield

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#21]
@chartgerink 

Hey!

You and Marcel were mentioning the number of marginal results per field/year last meeting, and some of them do have only a few. It's not really clear to me what to do about that though, except maybe indicate it in the graphs, nor what basis to use for what constitutes a 'good' amount, or if that is entirely arbitrary. Thankful for any insight from your side. Attached is a pdf with the number of p-values, and number of marginally significant results per year and subfield.

[marginals.table.pdf](https://github.com/chartgerink/2016marginal/files/1154054/marginals.table.pdf)

**Comment by chartgerink** [comment]
Thanks @Jaeoc! The PDF really makes it easier to respond, so thanks for thinking of me in this :100: 

I looked through the numbers, and most are okay. Forensic seems the most problematic (very low frequencies) and health in the early years too. Take note of these and add a note in the results, I'd say. It's especially important for assessing the fluctuations in those years/fields because they'll be more volatile, is my guess.

**Comment by Jaeoc** [comment]
Ok, thanks for taking a look!
