### ISSUE TITLE
Quick questions on your data extraction

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#8]
@chartgerink 

Writing the methods part, and have a few small questions:

- You told me the extraction of PDFs doesn't function well, but what was the problem more exactly again?
-  After standardizing the journal names (and updating old ones to their current ones), I see that there's data from 74 journals, while APA has 93 journals. Any insight on why some were not included/successfully extracted?

**Comment by chartgerink** [comment]
1. I downloaded only HTML, so that's part of why. Additionally, when there is a linebreak somewhere in `p=.05`, it splits it up into for example `p=` and `.05`, as a result of which you cannot find `p=.05` anymore. This not a problem in the HTML version.

2. Multiple reasons might be possible:
  * they've added new journals since I collected the list and downloaded the articles
  * I might've messed up in collecting the journals
  * I might've made some selection I've forgotten
  * variety of other reasons I can't think of right now

For the latter, I'd say to just refer to [this paper](http://www.mdpi.com/2306-5729/1/3/14) for collection details.
